"""schema_inicial

Revision ID: 2fa5e9d591a3
Revises:
Create Date: 2026-06-08 11:44:52.039921

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fa5e9d591a3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alumnos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("apellido", sa.String(length=100), nullable=False),
        sa.Column("dni", sa.String(length=20), nullable=False),
        sa.Column("legajo", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dni"),
        sa.UniqueConstraint("legajo", name="uq_alumno_legajo"),
    )
    op.create_table(
        "carreras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "lkp_estado_academico",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "lkp_estado_cursada",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "lkp_nivel_carrera",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "lkp_nucleo_carrera",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "lkp_tipo_cursada",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "lkp_user_roles",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "materias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("sigla", sa.String(length=20), nullable=True),
        sa.Column("creditos", sa.Integer(), nullable=True),
        sa.Column("nucleo", sa.String(length=50), nullable=True),
        sa.Column("horas_semanales", sa.Integer(), nullable=True),
        sa.Column("carga_horaria_total", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["nucleo"],
            ["lkp_nucleo_carrera.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "planes_de_estudio",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("carrera_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("nivel", sa.String(length=50), nullable=True),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("vigente", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["carrera_id"],
            ["carreras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nivel"],
            ["lkp_nivel_carrera.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("carrera_id", "anio", name="uq_plan_carrera_anio"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["role"],
            ["lkp_user_roles.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "alumno_carrera",
        sa.Column("alumno_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("fecha_ingreso", sa.Date(), nullable=True),
        sa.Column("estado_academico", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alumno_id"],
            ["alumnos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estado_academico"],
            ["lkp_estado_academico.key"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["planes_de_estudio.id"],
        ),
        sa.PrimaryKeyConstraint("alumno_id", "plan_id"),
    )
    op.create_table(
        "correlativas",
        sa.Column("materia_id", sa.Uuid(), nullable=False),
        sa.Column("requisito_id", sa.Uuid(), nullable=False),
        sa.Column("es_obligatoria", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requisito_id"],
            ["materias.id"],
        ),
        sa.PrimaryKeyConstraint("materia_id", "requisito_id"),
    )
    op.create_table(
        "cursadas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alumno_id", sa.Uuid(), nullable=False),
        sa.Column("materia_id", sa.Uuid(), nullable=False),
        sa.Column("carrera_id", sa.Uuid(), nullable=False),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("cuatrimestre", sa.String(length=5), nullable=False),
        sa.Column("comision", sa.String(length=20), nullable=True),
        sa.Column("tipo_cursada", sa.String(length=50), nullable=False),
        sa.Column("estado_cursada", sa.String(length=50), nullable=False),
        sa.Column("nota", sa.String(length=5), nullable=True),
        sa.Column("fecha_inscripcion", sa.Date(), nullable=True),
        sa.Column("fecha_cambio_estado", sa.DateTime(timezone=True), nullable=True),
        sa.Column("es_regular", sa.String(length=5), nullable=True),
        sa.Column("tipo_aprobacion", sa.String(length=50), nullable=True),
        sa.Column("anio_plan", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alumno_id"],
            ["alumnos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrera_id"],
            ["carreras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estado_cursada"],
            ["lkp_estado_cursada.key"],
        ),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_cursada"],
            ["lkp_tipo_cursada.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alumno_id",
            "materia_id",
            "carrera_id",
            "anio",
            "cuatrimestre",
            name="uq_cursada_alumno_materia_carrera_cuatrimestre",
        ),
    )
    op.create_table(
        "planes_materias",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("materia_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["planes_de_estudio.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "materia_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planes_materias")
    op.drop_table("cursadas")
    op.drop_table("correlativas")
    op.drop_table("alumno_carrera")
    op.drop_table("users")
    op.drop_table("planes_de_estudio")
    op.drop_table("materias")
    op.drop_table("lkp_user_roles")
    op.drop_table("lkp_tipo_cursada")
    op.drop_table("lkp_nucleo_carrera")
    op.drop_table("lkp_nivel_carrera")
    op.drop_table("lkp_estado_cursada")
    op.drop_table("lkp_estado_academico")
    op.drop_table("carreras")
    op.drop_table("alumnos")
    # ### end Alembic commands ###
