"""course_prerequisite uq_study_plan_degree_year

Revision ID: a58bc63f42f6
Revises: fc6f97d5203a
Create Date: 2026-05-29 20:53:53.796551

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a58bc63f42f6"
down_revision: str | Sequence[str] | None = "fc6f97d5203a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_prerequisite",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("prerequisite_id", sa.Uuid(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "course_id", "prerequisite_id"),
    )
    op.create_unique_constraint("uq_study_plan_degree_year", "study_plan", ["degree_id", "year"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_study_plan_degree_year", "study_plan", type_="unique")
    op.drop_table("course_prerequisite")
    # ### end Alembic commands ###
