"""schema_inicial

Revision ID: fc6f97d5203a
Revises:
Create Date: 2026-05-25 20:17:49.529916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc6f97d5203a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("abbreviation", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "degree",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "lkp_academic_status",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "lkp_enrollment_status",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "lkp_enrollment_type",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "study_plan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("degree_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["degree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("doc_id", sa.String(length=20), nullable=False),
        sa.Column("unq_id", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("degree_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("enrolled_at", sa.Date(), nullable=True),
        sa.Column("academic_status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_status"],
            ["lkp_academic_status.key"],
        ),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["degree.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_id"),
        sa.UniqueConstraint("unq_id", name="uq_student_unq_id"),
    )
    op.create_table(
        "study_plan_course",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plan.id"],
        ),
        sa.PrimaryKeyConstraint("plan_id", "course_id"),
    )
    op.create_table(
        "course_enrollment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("degree_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=5), nullable=False),
        sa.Column("section", sa.String(length=20), nullable=True),
        sa.Column("enrollment_type", sa.String(length=50), nullable=False),
        sa.Column("enrollment_status", sa.String(length=50), nullable=False),
        sa.Column("grade", sa.String(length=5), nullable=True),
        sa.Column("enrolled_at", sa.Date(), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_regular", sa.String(length=5), nullable=True),
        sa.Column("approval_type", sa.String(length=50), nullable=True),
        sa.Column("credits", sa.Integer(), nullable=True),
        sa.Column("plan_year", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["degree.id"],
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_status"],
            ["lkp_enrollment_status.key"],
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_type"],
            ["lkp_enrollment_type.key"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", "degree_id", "year", "term", name="uq_enrollment_student_course_degree_term"
        ),
    )
    # Seed lookup tables — datos estáticos requeridos por FK constraints
    op.bulk_insert(
        sa.table(
            "lkp_academic_status",
            sa.column("key", sa.String),
            sa.column("label", sa.String),
        ),
        [
            {"key": "alumno_regular", "label": "Alumno Regular"},
            {"key": "no_regular", "label": "No Regular"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "lkp_enrollment_status",
            sa.column("key", sa.String),
            sa.column("code", sa.String),
            sa.column("label", sa.String),
        ),
        [
            {"key": "inscripto", "code": "I", "label": "Inscripto"},
            {"key": "regular", "code": "R", "label": "Regular"},
            {"key": "promocionado", "code": "P", "label": "Promocionado"},
            {"key": "aprobado", "code": "A", "label": "Aprobado"},
            {"key": "pendiente_aprobacion", "code": "PA", "label": "Pendiente de Aprobación"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "lkp_enrollment_type",
            sa.column("key", sa.String),
            sa.column("label", sa.String),
        ),
        [
            {"key": "regular", "label": "Cursada Regular"},
            {"key": "libre", "label": "Libre"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_enrollment")
    op.drop_table("study_plan_course")
    op.drop_table("student")
    op.drop_table("study_plan")
    op.drop_table("lkp_enrollment_type")
    op.drop_table("lkp_enrollment_status")
    op.drop_table("lkp_academic_status")
    op.drop_table("degree")
    op.drop_table("course")
    # ### end Alembic commands ###
